[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos = { workspace = true }
leptos_router = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
